### ISSUE TITLE
doAction not working

### ISSUE THREAD

**Issue by LindaLawton** [anuviswan/LearningPoint#43]
How exactly are you testing this.   When I try to send the jwt to /doaction everything i try fails.

I have tried sending it as an authorization header and an authorization header bearer token.

Any tips on how exactly to get this to validate the token created?

**Comment by anuviswan** [comment]
@LindaLawton  Could you please provide exact project you are mentioning here. Unfortunately, this repository contains a lot of mini-projects and it is hard to understand which you are mentioning in this ticket.

**Comment by anuviswan** [comment]
@LindaLawton ,

BearerToken should be good to go. In your case, could you please provide a descriptive error ? One possible reason could be the second request ("/doaction") wasn't an HTTPS request.
